#!/usr/bin/env escript

main(Args) ->
  [Arg1,Arg2] = Args,
  code:add_path("./riak-erlang-client/ebin"),
  code:add_path("./riak-erlang-client/deps/riak_pb/ebin"),
  code:add_path("./riak-erlang-client/deps/protobuffs/ebin"),
  code:add_path("./riak-erlang-client/deps/meck/ebin"),
  %% io:format("~s~n", [code:which(riakc_pb_socket)]),
  %% io:format("~s~n", [code:which(riak_pb_ts_codec)]),
  %% io:format("~s~n", [Arg1]),
  %% io:format("~s~n", [Arg2]),

  {ok, Pid} = riakc_pb_socket:start_link(Arg1, 8087),  io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420113900000")]).
