#!/usr/bin/env escript

main(Args) ->
  [Arg1,Arg2] = Args,
  code:add_path("./riak-erlang-client/ebin"),
  code:add_path("./riak-erlang-client/deps/riak_pb/ebin"),
  code:add_path("./riak-erlang-client/deps/protobuffs/ebin"),
  code:add_path("./riak-erlang-client/deps/meck/ebin"),
  %% io:format("~s~n", [code:which(riakc_pb_socket)]),
  %% io:format("~s~n", [code:which(riak_pb_ts_codec)]),
  %% io:format("~s~n", [Arg1]),
  %% io:format("~s~n", [Arg2]),

  {ok, Pid} = riakc_pb_socket:start_link(Arg1, 8087),

io:fwrite("## select all columns~n", []),
io:fwrite("select * from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select * from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## select one column~n", []),
io:fwrite("select weather from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select weather from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## select multiple columns~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## Use integer for a column that is defined as double (will fail)~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25")]),
io:fwrite("~n", []),

io:fwrite("## use >~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0")]),
io:fwrite("~n", []),

io:fwrite("## use >=~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature >= 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature >= 25.0")]),
io:fwrite("~n", []),

io:fwrite("## use <~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature < 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature < 25.0")]),
io:fwrite("~n", []),

io:fwrite("## use <=~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature <= 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature <= 25.0")]),
io:fwrite("~n", []),

io:fwrite("## use =~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature = 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature = 25.0")]),
io:fwrite("~n", []),

io:fwrite("## use !=~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature != 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature != 25.0")]),
io:fwrite("~n", []),

io:fwrite("## do not use series in the query (will fail)~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0")]),
io:fwrite("~n", []),

io:fwrite("## use unbounded time (will fail)~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and temperature > 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and temperature > 25.0")]),
io:fwrite("~n", []),

io:fwrite("## do not use parenthesis (will fail)~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0 OR weather = 'hot'~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0 OR weather = 'hot'")]),
io:fwrite("~n", []),

io:fwrite("## use parenthesis~n", []),
io:fwrite("select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and (temperature > 25.0 OR weather = 'hot')~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select time, weather, temperature from " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and (temperature > 25.0 OR weather = 'hot')")]),
io:fwrite("~n", []),

io:fwrite("## count~n", []),
io:fwrite("select count(*) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select count(*) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## count with filter~n", []),
io:fwrite("select count(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select count(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0")]),
io:fwrite("~n", []),

io:fwrite("## avg~n", []),
io:fwrite("select avg(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select avg(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## avg with filter~n", []),
io:fwrite("select avg(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select avg(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0")]),
io:fwrite("~n", []),

io:fwrite("## max~n", []),
io:fwrite("select max(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select max(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## max with filter~n", []),
io:fwrite("select max(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select max(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0")]),
io:fwrite("~n", []),

io:fwrite("## min~n", []),
io:fwrite("select min(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select min(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## min with filter~n", []),
io:fwrite("select min(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select min(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0")]),
io:fwrite("~n", []),

io:fwrite("## stddev~n", []),
io:fwrite("select stddev(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select stddev(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## stddev with filter~n", []),
io:fwrite("select stddev(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select stddev(temperature) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000 and temperature > 25.0")]),
io:fwrite("~n", []),

io:fwrite("## arithmetic - numerics~n", []),
io:fwrite("select 555, 1.1, 1e1, 1.123e-2 from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select 555, 1.1, 1e1, 1.123e-2 from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## arithmetic - operations~n", []),
io:fwrite("select temperature, temperature + 5, temperature - 5, temperature * 2, temperature / 2, -temperature, (temperature + 5)/2, (temperature * 10)/(2 - 100) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select temperature, temperature + 5, temperature - 5, temperature * 2, temperature / 2, -temperature, (temperature + 5)/2, (temperature * 10)/(2 - 100) from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []),

io:fwrite("## arithmetic (will fail)~n", []),
io:fwrite("select temperature + weather from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000~n", []),
io:format("~p~n", [riakc_ts:query(Pid, "select temperature + weather from  " ++ Arg2 ++ " where myfamily = 'family1' and myseries = 'series1' and time >= 1420113600000 and time <= 1420119300000")]),
io:fwrite("~n", []).
